@echo off
echo Cleaning project...
if exist .next rmdir /s /q .next
echo Installing dependencies...
call npm install
echo Building project...
call npm run build
echo Starting development server...
call npm run dev 